name: Test Pull Requests
on: 
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Execute test cases
        working-directory: ./app-to-test 
        run: |
          npm install
          npm test -- --coverage --watchAll=false
  run-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Check out test case repo
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SMOKE_TEST_KEY }}"
          git clone git@github.com:BackToTech-Study/TestsForDefaultReactApp.git
      - name: Start app
        working-directory: ./app-to-test 
        run: |
          npm install
          npm start & sleep 10
      - name: Run test cases
        working-directory: ./TestsForDefaultReactApp 
        run: |
          npm install
          npx cypress run        