name: Test Pull Requests
on: 
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: cd app-to-test
      - run: npm install
      - run: npm test -- --coverage --watchAll=false