name: Test Pull Requests
on: 
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Execute test cases
        working-directory: ./app-to-test 
        run: |
          npm install
          npm test -- --coverage --watchAll=false
  run-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Execute test cases
        working-directory: ./app-to-test 
        run: |
          npm start 